import { defineConfig } from 'orval';

/**
 * Generates a typed Angular HttpClient client + models from the API's OpenAPI
 * document into `src/lib/generated/`. The spec is emitted by the API build
 * (`apps/api/openapi/Api.json`), so regeneration needs no running backend.
 *
 * Regenerate with: `npx nx run data-access:generate-api`
 * Never hand-edit files under `src/lib/generated/`.
 */
export default defineConfig({
  api: {
    input: '../../../apps/api/openapi/Api.json',
    output: {
      mode: 'split',
      target: './src/lib/generated/api.ts',
      schemas: './src/lib/generated/model',
      client: 'angular',
      clean: true,
      // Emit relative paths (e.g. `/api/todos`) so the dev proxy and the
      // nginx reverse proxy in the container stack both resolve same-origin.
      baseUrl: '',
      override: {
        header: () => [
          'Generated by orval from the API OpenAPI spec — DO NOT EDIT.',
          'Run `nx run data-access:generate-api` to regenerate.',
        ],
      },
    },
  },
});
